name: "Code scanning - action"

on: [push]

jobs:
  CodeQL-Build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      pull-requests: read

    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.102

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@main
      with:
        languages: python
        config-file: ./.github/workflows/test1.yaml
      
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

#     - name: Build Python project
#       run: python mlops.ipynb build
      
    - name: Build Python project
      run: |
        jupyter nbconvert --to script mlops.ipynb
        python mlops.py build

